import RecoilRootWrapper from '@components/RecoilWrapper/RecoilRootWrapper';

export const fetchCache = "only-no-store";

export const metadata = {
  title: "한국조폐공사 결제플랫폼",
  description: "Generated by finger Corporation",
};

export default async function RootLayout({ children }) {
  return (
    <html>
      <body suppressHydrationWarning={true}>
        <RecoilRootWrapper>
          {children}
        </RecoilRootWrapper>
      </body>
    </html>
  )
}

